from dataclasses import dataclass, field
from enum import Enum, auto
import time
import random
import logging
from savi.preprocessor import Preprocessor
from savi.detector import detect_primary_saccade

logger = logging.getLogger("savi.protocol")

class BlockType(Enum):
    OVERLAP    = "overlap"
    GAP        = "gap"
    ANTISACCADE = "antisaccade"

class TrialState(Enum):
    FIXATION_CHECK  = auto()   # waiting for subject to acquire fixation
    FIXATION_HOLD   = auto()   # fixation acquired, holding for stability
    GAP_BLANK       = auto()   # fixation dot removed, screen blank (gap only)
    TARGET_ON       = auto()   # peripheral target presented
    POST_TARGET     = auto()   # target off, collecting post-saccade frames
    ITI             = auto()   # inter-trial interval, screen blank
    COMPLETE        = auto()   # trial finished
    ABORTED         = auto()   # trial aborted (fixation lost before target)

@dataclass
class TrialSpec:
    """
    Defines a single trial's stimulus parameters.
    Generated by BlockRunner before the trial begins.
    """
    block_type: BlockType
    trial_number: int          # 1-indexed within block
    block_number: int          # 1 = Overlap, 2 = Gap, 3 = Antisaccade
    target_direction: str      # "left" or "right"
    target_amplitude_deg: float  # degrees from center (always positive)
    gap_duration_ms: float     # 0.0 for Overlap; 200.0 for Gap; 0.0 for Antisaccade
    iti_duration_ms: float     # inter-trial interval in ms

@dataclass
class TrialLog:
    """
    Complete record of one trial. Written after trial completes.
    This is the primary data structure for the paper's methods section.
    """
    spec: TrialSpec

    # Timing (all time.perf_counter() values, seconds)
    t_trial_start: float        # when FIXATION_CHECK began
    t_fixation_acquired: float  # when FIXATION_HOLD began
    t_target_onset: float       # when TARGET_ON state entered
                                # CRITICAL: must be recorded at the moment
                                # the caller signals target display, not at
                                # QTimer callback. In headless mode, this is
                                # time.perf_counter() at state transition.
                                # In UI mode (v0.1.0-ui), this will be
                                # overwritten by paintEvent() timestamp.
    t_trial_end: float          # when COMPLETE or ABORTED state entered

    # Raw data
    frames: list                # list[GazeFrame] — all frames during trial
    n_frames: int               # len(frames)

    # Processed outputs (populated by protocol after detector runs)
    trace: object | None        # GazeTrace | None
    saccade: object | None      # DetectedSaccade | None

    # Trial outcome
    is_usable: bool             # trace.is_usable if trace exists, else False
    aborted: bool               # True if ABORTED state reached
    abort_reason: str           # "" if not aborted

    # Antisaccade-specific (populated only for BlockType.ANTISACCADE)
    is_correct_antisaccade: bool | None  # None for non-antisaccade trials
    # True if direction != expected_direction AND is_valid
    # (correct antisaccade = eye went to opposite side of target)

@dataclass
class BlockResult:
    """
    Aggregated result of one complete block.
    """
    block_type: BlockType
    block_number: int
    trials: list               # list[TrialLog]
    n_total: int
    n_usable: int
    n_aborted: int
    t_block_start: float
    t_block_end: float

# Block trial counts
# Source: savi_clinical_protocol_spec.md
# Thread 3 — standard clinical saccade battery
OVERLAP_TRIAL_COUNT     = 22
GAP_TRIAL_COUNT         = 22
ANTISACCADE_TRIAL_COUNT = 33

# Block order: Overlap → Gap → Antisaccade
# Source: 2025 Brain & Behavior paper — fatigue impairs antisaccade,
# not prosaccade. Antisaccade must run last.
BLOCK_ORDER = [BlockType.OVERLAP, BlockType.GAP, BlockType.ANTISACCADE]

# Target amplitudes (degrees) — randomly drawn per trial
# Source: savi_clinical_protocol_spec.md
TARGET_AMPLITUDES_DEG = [10.0, 15.0, 20.0]

# Timing parameters (milliseconds)
# Source: savi_clinical_protocol_spec.md; Fischer 1997
FIXATION_HOLD_DURATION_MS  = 800.0   # ms fixation must be stable before target
FIXATION_WINDOW_DEG        = 2.5     # degrees — fixation acceptance window
GAP_DURATION_MS            = 200.0   # ms blank screen in Gap block (Fischer 1997)
TARGET_DURATION_MS         = 1000.0  # ms target remains on screen
POST_TARGET_DURATION_MS    = 500.0   # ms post-target collection window
ITI_DURATION_MS_MIN        = 1000.0  # ms — minimum inter-trial interval
ITI_DURATION_MS_MAX        = 1500.0  # ms — maximum (uniform random jitter)

# Fixation detection
# A frame counts as fixating if:
#   abs(gaze_x_deg) < FIXATION_WINDOW_DEG AND
#   abs(gaze_y_deg) < FIXATION_WINDOW_DEG AND
#   NOT blink AND confidence > 0.5
FIXATION_CONFIDENCE_MIN = 0.5

# Minimum valid trials per block to proceed
# Source: savi_clinical_protocol_spec.md
MIN_USABLE_TRIALS = {
    BlockType.OVERLAP:     15,
    BlockType.GAP:         15,
    BlockType.ANTISACCADE: 18,
}

class TrialEngine:
    """
    Headless single-trial state machine.

    Usage:
        engine = TrialEngine(spec)
        engine.start()

        # Every time a new GazeFrame arrives from the tracker:
        result = engine.push_frame(gaze_frame)
        if result is not None:
            # trial is complete — result is a TrialLog

    The engine does not own a timer. The caller drives it by
    pushing frames. State transitions happen based on elapsed
    time measured from time.perf_counter() at each push_frame call.

    In production, the UI layer will:
      1. Subscribe to the tracker queue
      2. Push each frame to the active TrialEngine
      3. On completion, store the TrialLog and start the next trial
    """

    def __init__(self, spec: TrialSpec):
        self.spec = spec
        self.state = TrialState.FIXATION_CHECK
        self.frames: list = []

        # Timestamps
        self.t_trial_start: float = 0.0
        self.t_fixation_acquired: float = 0.0
        self.t_gap_start: float = 0.0
        self.t_target_onset: float = 0.0
        self.t_post_target_start: float = 0.0
        self.t_iti_start: float = 0.0

        # Fixation tracking
        self._fixation_hold_frames: int = 0
        self._fixation_hold_required: int = int(
            (FIXATION_HOLD_DURATION_MS / 1000.0) * 30.0
        )

        self._preprocessor = Preprocessor()
        self._complete = False
        self._on_target_onset = None

    def start(self):
        """Call once before pushing any frames."""
        self.t_trial_start = time.perf_counter()
        self.state = TrialState.FIXATION_CHECK
        logger.debug(
            f"Trial {self.spec.trial_number} started — "
            f"{self.spec.block_type.value} "
            f"{self.spec.target_direction} {self.spec.target_amplitude_deg}°"
        )

    def set_onset_callback(self, cb) -> None:
        """
        Register a callback to be invoked at the moment the UI
        is about to render the target stimulus.

        The callback signature: cb() → None
        The UI's paintEvent() calls set_target_onset(time.perf_counter())
        immediately after this callback fires.

        This is the only way t_target_onset is set precisely.
        The headless fallback (time.perf_counter() at state transition)
        is overwritten by the UI layer via set_target_onset().

        Source: savi_clinical_protocol_spec.md — CRITICAL TIMING ACTION
        "Record IMMEDIATELY inside the paintEvent() that renders the target dot."
        """
        self._on_target_onset = cb

    def set_target_onset(self, t: float) -> None:
        """
        Overwrite t_target_onset with the timestamp recorded inside
        paintEvent() — the closest measurable approximation to actual
        photon emission.

        Called by StimulusWindow.paintEvent() only.
        Never called from QTimer callbacks.

        At 30fps this eliminates up to 33ms of render-pipeline latency
        from the headless approximation.
        """
        self.t_target_onset = t

    def push_frame(self, frame) -> "TrialLog | None":
        """
        Push one GazeFrame into the state machine.

        Returns TrialLog when the trial reaches COMPLETE or ABORTED.
        Returns None while the trial is still running.
        """
        if self._complete:
            return None

        self.frames.append(frame)
        now = time.perf_counter()

        if self.state == TrialState.FIXATION_CHECK:
            return self._handle_fixation_check(frame, now)

        elif self.state == TrialState.FIXATION_HOLD:
            return self._handle_fixation_hold(frame, now)

        elif self.state == TrialState.GAP_BLANK:
            return self._handle_gap_blank(frame, now)

        elif self.state == TrialState.TARGET_ON:
            return self._handle_target_on(frame, now)

        elif self.state == TrialState.POST_TARGET:
            return self._handle_post_target(frame, now)

        elif self.state == TrialState.ITI:
            return self._handle_iti(frame, now)

        return None

    def _is_fixating(self, frame) -> bool:
        """
        Returns True if this frame represents a valid central fixation.
        Uses calibrated gaze if available, falls back to raw gaze.
        """
        if frame.blink:
            return False
        if frame.confidence < FIXATION_CONFIDENCE_MIN:
            return False

        gaze_x = frame.cal_x_deg if frame.calibration_applied else frame.gaze_x_deg
        gaze_y = frame.cal_y_deg if frame.calibration_applied else frame.gaze_y_deg

        return (
            abs(gaze_x) < FIXATION_WINDOW_DEG and
            abs(gaze_y) < FIXATION_WINDOW_DEG
        )

    def _handle_fixation_check(self, frame, now: float) -> "TrialLog | None":
        """
        Wait for subject to fixate center.
        No timeout — trial waits indefinitely for fixation.
        (Timeout policy is the caller's responsibility.)
        """
        if self._is_fixating(frame):
            self._fixation_hold_frames = 1
            self.t_fixation_acquired = now
            self.state = TrialState.FIXATION_HOLD
            logger.debug(f"Trial {self.spec.trial_number}: fixation acquired")
        return None

    def _handle_fixation_hold(self, frame, now: float) -> "TrialLog | None":
        """
        Fixation must remain stable for FIXATION_HOLD_DURATION_MS.
        If fixation breaks before hold completes, return to FIXATION_CHECK.
        """
        if not self._is_fixating(frame):
            # Fixation broken — reset
            self._fixation_hold_frames = 0
            self.state = TrialState.FIXATION_CHECK
            logger.debug(f"Trial {self.spec.trial_number}: fixation broken, resetting")
            return None

        self._fixation_hold_frames += 1
        elapsed_ms = (now - self.t_fixation_acquired) * 1000.0

        if elapsed_ms >= FIXATION_HOLD_DURATION_MS:
            # Fixation hold complete — advance state
            if self.spec.gap_duration_ms > 0.0:
                # Gap block: blank screen before target
                self.t_gap_start = now
                self.state = TrialState.GAP_BLANK
                logger.debug(f"Trial {self.spec.trial_number}: entering GAP_BLANK")
            else:
                # Overlap or Antisaccade: go directly to target
                self.t_target_onset = now
                if self._on_target_onset:
                    self._on_target_onset()
                self.state = TrialState.TARGET_ON
                logger.debug(f"Trial {self.spec.trial_number}: entering TARGET_ON")

        return None

    def _handle_gap_blank(self, frame, now: float) -> "TrialLog | None":
        """
        Gap block only. Fixation dot is off. Screen is blank.
        Wait GAP_DURATION_MS then present target.
        No fixation check during gap — subject is expected to drift slightly.
        """
        elapsed_ms = (now - self.t_gap_start) * 1000.0
        if elapsed_ms >= self.spec.gap_duration_ms:
            self.t_target_onset = now
            if self._on_target_onset:
                self._on_target_onset()
            self.state = TrialState.TARGET_ON
            logger.debug(f"Trial {self.spec.trial_number}: gap complete, TARGET_ON")
        return None

    def _handle_target_on(self, frame, now: float) -> "TrialLog | None":
        """
        Target is on screen. Collect frames until TARGET_DURATION_MS elapses.
        """
        elapsed_ms = (now - self.t_target_onset) * 1000.0
        if elapsed_ms >= TARGET_DURATION_MS:
            self.t_post_target_start = now
            self.state = TrialState.POST_TARGET
            logger.debug(f"Trial {self.spec.trial_number}: entering POST_TARGET")
        return None

    def _handle_post_target(self, frame, now: float) -> "TrialLog | None":
        """
        Target is off. Collect post-saccade settling frames.
        """
        elapsed_ms = (now - self.t_post_target_start) * 1000.0
        if elapsed_ms >= POST_TARGET_DURATION_MS:
            self.t_iti_start = now
            self.state = TrialState.ITI
            logger.debug(f"Trial {self.spec.trial_number}: entering ITI")
        return None

    def _handle_iti(self, frame, now: float) -> "TrialLog | None":
        """
        Inter-trial interval. Screen blank.
        When elapsed >= spec.iti_duration_ms, finalize and return TrialLog.
        """
        elapsed_ms = (now - self.t_iti_start) * 1000.0
        if elapsed_ms >= self.spec.iti_duration_ms:
            return self._finalize()
        return None

    def _finalize(self) -> TrialLog:
        """
        Run preprocessor and detector on collected frames.
        Build and return the TrialLog.
        """
        self._complete = True
        self.state = TrialState.COMPLETE
        t_end = time.perf_counter()

        # Run signal processing
        trace = None
        saccade = None
        is_usable = False

        if len(self.frames) >= 5:
            try:
                trace = self._preprocessor.process_trial(
                    self.frames,
                    session_id="headless",
                    trial_id=self.spec.trial_number,
                    t_target_onset_s=self.t_target_onset
                )
                is_usable = trace.is_usable

                if is_usable:
                    saccade = detect_primary_saccade(
                        trace,
                        t_target_onset_s=self.t_target_onset,
                        expected_direction=self.spec.target_direction
                    )
            except Exception as e:
                logger.error(
                    f"Trial {self.spec.trial_number} processing failed: {e}"
                )

        # Antisaccade correctness
        is_correct_antisaccade = None
        if self.spec.block_type == BlockType.ANTISACCADE and saccade is not None:
            # Correct antisaccade: eye went to OPPOSITE side of target
            # direction field on DetectedSaccade is actual eye direction
            # expected_direction is where the target appeared
            # Correct = they do NOT match
            went_opposite = (saccade.direction != self.spec.target_direction)
            is_correct_antisaccade = went_opposite and saccade.is_valid

        log = TrialLog(
            spec=self.spec,
            t_trial_start=self.t_trial_start,
            t_fixation_acquired=self.t_fixation_acquired,
            t_target_onset=self.t_target_onset,
            t_trial_end=t_end,
            frames=self.frames,
            n_frames=len(self.frames),
            trace=trace,
            saccade=saccade,
            is_usable=is_usable,
            aborted=False,
            abort_reason="",
            is_correct_antisaccade=is_correct_antisaccade
        )

        logger.info(
            f"Trial {self.spec.trial_number} complete — "
            f"usable={is_usable} "
            f"saccade={'found' if saccade else 'none'} "
            f"latency={saccade.latency_ms:.1f}ms" if saccade else ""
        )

        return log

class BlockRunner:
    """
    Runs one complete block (Overlap, Gap, or Antisaccade).

    Generates trial specs, manages TrialEngine lifecycle,
    and returns a BlockResult when all trials complete.

    Usage:
        runner = BlockRunner(block_type=BlockType.OVERLAP, block_number=1)
        runner.start()

        # In the frame loop:
        result = runner.push_frame(gaze_frame)
        if result is not None:
            # block is complete — result is a BlockResult
    """

    def __init__(self, block_type: BlockType, block_number: int):
        self.block_type = block_type
        self.block_number = block_number
        self.t_block_start: float = 0.0

        self._trial_count = {
            BlockType.OVERLAP:     OVERLAP_TRIAL_COUNT,
            BlockType.GAP:         GAP_TRIAL_COUNT,
            BlockType.ANTISACCADE: ANTISACCADE_TRIAL_COUNT,
        }[block_type]

        self._trials: list[TrialLog] = []
        self._current_engine: TrialEngine | None = None
        self._current_trial_number: int = 0
        self._complete = False

        # Pre-generate direction sequence to satisfy "no more than 3 consecutive same-direction trials occur"
        self._directions = self._generate_balanced_directions(self._trial_count)

    def _generate_balanced_directions(self, n_trials: int) -> list[str]:
        # Generate pairs of left/right
        pairs = []
        for _ in range(n_trials // 2):
            pairs.append(["left", "right"])
        
        directions = []
        for p in pairs:
            directions.extend(p)
        if n_trials % 2 != 0:
            directions.append(random.choice(["left", "right"]))
            
        # Try shuffling until valid (no more than 3 consecutive same-direction)
        for _ in range(100):
            random.shuffle(directions)
            consec = 1
            max_consec = 1
            for i in range(1, len(directions)):
                if directions[i] == directions[i-1]:
                    consec += 1
                    max_consec = max(max_consec, consec)
                else:
                    consec = 1
            if max_consec <= 3:
                return directions
        return directions

    def start(self):
        self.t_block_start = time.perf_counter()
        self._start_next_trial()

    def push_frame(self, frame) -> "BlockResult | None":
        if self._complete or self._current_engine is None:
            return None

        result = self._current_engine.push_frame(frame)

        if result is not None:
            # Trial complete
            self._trials.append(result)

            if self._current_trial_number >= self._trial_count:
                # All trials done
                return self._finalize()
            else:
                self._start_next_trial()

        return None

    def _start_next_trial(self):
        self._current_trial_number += 1
        spec = self._generate_spec(self._current_trial_number)
        self._current_engine = TrialEngine(spec)
        self._current_engine.start()
        logger.info(
            f"Block {self.block_number} ({self.block_type.value}) — "
            f"starting trial {self._current_trial_number}/"
            f"{self._trial_count}"
        )

    def _generate_spec(self, trial_number: int) -> TrialSpec:
        """
        Generate a randomized trial spec.

        Direction: alternating left/right with random jitter.
        Use a balanced sequence: shuffle pairs of (left, right) so
        that no more than 3 consecutive same-direction trials occur.
        Amplitude: uniform random from TARGET_AMPLITUDES_DEG.
        ITI: uniform random between ITI_DURATION_MS_MIN and MAX.
        """
        # Balanced direction assignment
        idx = (trial_number - 1) % len(self._directions)
        direction = self._directions[idx]

        amplitude = random.choice(TARGET_AMPLITUDES_DEG)

        gap_ms = GAP_DURATION_MS if self.block_type == BlockType.GAP else 0.0

        iti_ms = random.uniform(ITI_DURATION_MS_MIN, ITI_DURATION_MS_MAX)

        return TrialSpec(
            block_type=self.block_type,
            trial_number=trial_number,
            block_number=self.block_number,
            target_direction=direction,
            target_amplitude_deg=amplitude,
            gap_duration_ms=gap_ms,
            iti_duration_ms=iti_ms
        )

    def _finalize(self) -> BlockResult:
        self._complete = True
        t_end = time.perf_counter()

        n_usable = sum(1 for t in self._trials if t.is_usable)
        n_aborted = sum(1 for t in self._trials if t.aborted)

        result = BlockResult(
            block_type=self.block_type,
            block_number=self.block_number,
            trials=self._trials,
            n_total=len(self._trials),
            n_usable=n_usable,
            n_aborted=n_aborted,
            t_block_start=self.t_block_start,
            t_block_end=t_end
        )

        logger.info(
            f"Block {self.block_number} ({self.block_type.value}) complete — "
            f"{n_usable}/{len(self._trials)} usable trials"
        )
        return result

class SessionRunner:
    """
    Runs the full 3-block test battery in the locked order:
    Overlap → Gap → Antisaccade.

    Usage:
        session = SessionRunner()
        session.start()

        # In the frame loop:
        result = session.push_frame(gaze_frame)
        if result is not None:
            # full battery complete — result is list[BlockResult]
    """

    def __init__(self):
        self._block_results: list[BlockResult] = []
        self._current_block_idx: int = 0
        self._current_runner: BlockRunner | None = None
        self._complete = False

    def start(self):
        self._start_next_block()

    def push_frame(self, frame) -> "list[BlockResult] | None":
        if self._complete or self._current_runner is None:
            return None

        result = self._current_runner.push_frame(frame)

        if result is not None:
            self._block_results.append(result)
            self._current_block_idx += 1

            if self._current_block_idx >= len(BLOCK_ORDER):
                self._complete = True
                logger.info("Full test battery complete.")
                return self._block_results
            else:
                self._start_next_block()

        return None

    def _start_next_block(self):
        block_type = BLOCK_ORDER[self._current_block_idx]
        runner = BlockRunner(
            block_type=block_type,
            block_number=self._current_block_idx + 1
        )
        self._current_runner = runner
        runner.start()
        logger.info(
            f"Starting block {self._current_block_idx + 1}/3: "
            f"{block_type.value}"
        )
